const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { readResults } = require('allure-js-commons');

// Replace with your Teams webhook URL
const webhookUrl = 'webhook URL';

// Path to the generated Allure report
const reportUrl = 'http://127.0.0.1:8080';
const resultsPath = './allure-report/history';

// Function to send the report to Teams
async function sendReport() 
{
  const rawData = fs.readFileSync(path.join(resultsPath, 'history-trend.json'));
  const results = JSON.parse(rawData);
  console.log(results)
  // Extract test execution metadata
  const totalTests = results[0].data.total;
  const passedTests = results[0].data.passed;
  const failedTests = results[0].data.failed;
  const skippedTests = results[0].data.skipped;
  // console.log('Total Tests: '+totalTests);
  // console.log('Passed Tests: '+passedTests);
  // console.log('Failed Tests: '+failedTests);
  if (totalTests !== null || totalTests!== undefined) 
    {
  const message = {
    
    "@type": "MessageCard",
    "@context": "https://schema.org/extensions",
    "summary": "Test Execution Results",
    "sections": [
      {
        "activityTitle": "Playwright Test Execution Results",
        // "activitySubtitle": "Generated by Playwright",
        "text": `Here is the latest Allure report: [Allure Report](${reportUrl})`,
        "facts": [
          { "name": "Total Tests:", "value": totalTests },
          { "name": "Passed Tests:", "value": passedTests },
          { "name": "Failed Tests:", "value": failedTests },
          { "name": "Skipped Tests:", "value": skippedTests }
        ],
        "markdown": true
      }
    ]
  };
  try {
    await axios.post(webhookUrl, message);
    console.log('Report sent to Teams successfully!');
  } catch (error) {
    console.error('Error sending report to Teams:', error);
  }
}
}






sendReport();